const express = require("express");

const app = express();

app.get("/api/players", (req, res) => {
  const players = [
    {
      id: 0,
      firstName: "Devin",
      lastName: "Booker",
      jerseyNumber: "#1",
      currentTeam: "Phoenix Suns",
      position: "Shooting Guard",
      height: "6ft. 5in.",
      weight: "206 lbs.",
      birthDate: "October 30, 1996",
      experience: "5 yrs.",
      college: "Kentucky",
    },
    {
      id: 1,
      firstName: "Mikal",
      lastName: "Bridges",
      jerseyNumber: "#25",
      currentTeam: "Phoenix Suns",
      position: "Small Forward",
      height: "6ft. 6in.",
      weight: "209 lbs.",
      birthDate: "August 30, 1996",
      experience: "2 yrs.",
      college: "Villanova",
    },
    {
      id: 2,
      firstName: "Jae",
      lastName: "Crowder",
      jerseyNumber: "#99",
      currentTeam: "Phoenix Suns",
      position: "Power Forward",
      height: "6ft. 6in.",
      weight: "235 lbs.",
      birthDate: "July 6, 1990",
      experience: "8 yrs.",
      college: "Marquette",
    },
    {
      id: 3,
      firstName: "Cameron",
      lastName: "Johnson",
      jerseyNumber: "#23",
      currentTeam: "Phoenix Suns",
      position: "Power Forward",
      height: "6ft. 8in.",
      weight: "210 lbs.",
      birthDate: "March 3, 1996",
      experience: "1 yr.",
      college: "Pitt, UNC",
    },
    {
      id: 4,
      firstName: "Cameron",
      lastName: "Payne",
      jerseyNumber: "#15",
      currentTeam: "Phoenix Suns",
      position: "Point Guard",
      height: "6ft. 1in.",
      weight: "183 lbs.",
      birthDate: "August 8, 1994",
      experience: "5 yrs.",
      college: "Murray State",
    },
    {
      id: 5,
      firstName: "Jevon",
      lastName: "Carter",
      jerseyNumber: "#4",
      currentTeam: "Phoenix Suns",
      position: "Point Guard",
      height: "6ft. 1in.",
      weight: "200 lbs.",
      birthDate: "September 14, 1995",
      experience: "2 yrs.",
      college: "West Virginia",
    },
    {
      id: 6,
      firstName: "Dario",
      lastName: "Saric",
      jerseyNumber: "#20",
      currentTeam: "Phoenix Suns",
      position: "Center",
      height: "6ft. 10in.",
      weight: "225 lbs.",
      birthDate: "April 8, 1994",
      experience: "4 yrs.",
      college: "N/A",
    },
    {
      id: 7,
      firstName: "Frank",
      lastName: "Kaminsky",
      jerseyNumber: "#8",
      currentTeam: "Phoenix Suns",
      position: "Center",
      height: "7ft. 0in.",
      weight: "240 lbs.",
      birthDate: "April 4, 1993",
      experience: "5 yrs.",
      college: "Wisconsin",
    },
    {
      id: 8,
      firstName: "Langston",
      lastName: "Galloway",
      jerseyNumber: "#2",
      currentTeam: "Phoenix Suns",
      position: "Shooting Guard",
      height: "6ft. 1in.",
      weight: "200 lbs.",
      birthDate: "December 9, 1991",
      experience: "6 yrs.",
      college: "Saint Joseph's",
    },
    {
      id: 9,
      firstName: "Torrey",
      lastName: "Craig",
      jerseyNumber: "#12",
      currentTeam: "Phoenix Suns",
      position: "Small Forward",
      height: "6ft. 7in.",
      weight: "221 lbs.",
      birthDate: "December 19, 1990",
      experience: "3 yrs.",
      college: "USC Upstate",
    },
    {
      id: 10,
      firstName: "E'Twaun",
      lastName: "Moore",
      jerseyNumber: "#55",
      currentTeam: "Phoenix Suns",
      position: "Shooting Guard",
      height: "6ft. 3in.",
      weight: "191 lbs.",
      birthDate: "February 25, 1989",
      experience: "9 yrs.",
      college: "Purdue",
    },
    {
      id: 11,
      firstName: "Jalen",
      lastName: "Smith",
      jerseyNumber: "#10",
      currentTeam: "Phoenix Suns",
      position: "Power Forward",
      height: "6ft. 10in.",
      weight: "215 lbs.",
      birthDate: "March 16, 2000",
      experience: "Rookie",
      college: "Maryland",
    },
    {
      id: 12,
      firstName: "Abdel",
      lastName: "Nader",
      jerseyNumber: "#11",
      currentTeam: "Phoenix Suns",
      position: "Small Forward",
      height: "6ft. 5in.",
      weight: "225 lbs.",
      birthDate: "September 25, 1993",
      experience: "3 yrs.",
      college: "Northern Illinois, Iowa State",
    },
    {
      id: 13,
      firstName: "Ty-Shon",
      lastName: "Alexander",
      jerseyNumber: "#0",
      currentTeam: "Phoenix Suns",
      position: "Shooting Guard",
      height: "6ft. 3in.",
      weight: "195 lbs.",
      birthDate: "July 16, 1998",
      experience: "Rookie",
      college: "Creighton",
    },
    {
      id: 14,
      firstName: "Chris",
      lastName: "Paul",
      jerseyNumber: "#3",
      currentTeam: "Phoenix Suns",
      position: "Point Guard",
      height: "6ft. 0in.",
      weight: "175 lbs.",
      birthDate: "May 6, 1985",
      experience: "15 yrs.",
      college: "Wake Forest",
    },
    {
      id: 15,
      firstName: "Deandre",
      lastName: "Ayton",
      jerseyNumber: "#22",
      currentTeam: "Phoenix Suns",
      position: "Center",
      height: "6ft. 11in.",
      weight: "250 lbs.",
      birthDate: "July 23, 1998",
      experience: "2 yrs.",
      college: "Arizona",
    },
  ];

  res.json(players);
});

const port = 3001;

app.listen(port, () => console.log(`Server started on port ${port}`));
